name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    name: Release Drafter
    environment: release-drafter
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7.6.0
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Update version in package.json
        env:
          VERSION: ${{ steps.drafter.outputs.resolved_version }}
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json

      - name: Commit changes
        env:
          VERSION: ${{ steps.drafter.outputs.resolved_version }}
        run: |
          if ! git diff --quiet; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Bump version to $VERSION"
            git push
          fi
